exports.personForm = function(d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Form demo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Person Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Name</legend>
                        <label>Who</label>
                        <input class="w3-input w3-round" type="text" name="who">
                        <label>Date</label>
                        <input class="w3-input w3-round" type="text" name="date">
                        <label>Task</label>
                        <input class="w3-input w3-round" type="text" name="task">
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by RPCW2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
            `
    return pagHTML
}

exports.TaskListTable = function(d, toDo, completed){
    let pagHTML = ""
    for(let i=0; i < toDo.length ; i++){
        pagHTML += `
            <tr>
                <td>${toDo[i].dateDued}</td><td>${toDo[i].who}</td><td style="width:50%;">${toDo[i].what}</td>
                <td>
                <div class="w3-bar">
                    <button class="w3-btn w3-yellow w3-tiny w3-padding-small w3-bar-item w3-border w3-border-black" onclick="showHide('toDo','${toDo[i].id}')">Edit</button>
                    <form class="w3-container w3-bar-item" method="POST" style="padding:0px">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="db" value="toDo">
                        <input type="hidden" name="id" value="${toDo[i].id}">
                        <button class="w3-btn w3-yellow w3-tiny w3-padding-small w3-border w3-border-black" type="submit">Delete</button>
                    </form>
                    <form class="w3-container w3-bar-item" method="POST" style="padding:0px">
                        <input type="hidden" name="_method" value="CHECK">
                        <input type="hidden" name="db" value="toDo">
                        <input type="hidden" name="id" value="${toDo[i].id}">
                        <input type="hidden" name="dateDued" value="${toDo[i].dateDued}">
                        <input type="hidden" name="who" value="${toDo[i].who}">
                        <input type="hidden" name="what" value="${toDo[i].what}">
                        <button class="w3-btn w3-yellow w3-tiny w3-padding-small w3-border w3-border-black" type="submit">Check</button>
                    </form>
                </div>
                </td>
            </tr>
    `
    }
    for(let i=0; i < completed.length ; i++){
        pagHTML += `
            <tr>
                <td>${completed[i].dateDued}</td><td>${completed[i].who}</td><td style="width:50%;">${completed[i].what}</td>
                <td>
                <div class="w3-bar">
                <button class="w3-btn w3-yellow w3-tiny w3-padding-small w3-bar-item w3-border w3-border-black" onclick="showHide('completed','${completed[i].id}')">Edit</button>
                <form class="w3-container w3-bar-item" method="POST" style="padding:0px">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="db" value="completed">
                    <input type="hidden" name="id" value="${completed[i].id}">
                    <button class="w3-btn w3-yellow w3-tiny w3-padding-small w3-border w3-border-black" type="submit">Delete</button>
                </form>
                </div>
                </td>
            </tr>
    `
    }

    pagHTML += `
        </table>
                    </div>
                </div>
                <footer class="w3-container w3-blue w3-center w3-bottom">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

